services:
  - type: web
    name: payment-tracker-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_USER_ID
        sync: false
      - key: TELEGRAM_GROUP_ID
        sync: false
